name: LLVM build

on:
  workflow_dispatch:

env:
  CC: clang
  CXX: clang++
  MAKE: make

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: building
        run: |
          sudo apt install build-essential ninja-build -y
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/llvm-project-18.1.8.src.tar.xz
          tar xf llvm-project-18.1.8.src.tar.xz
          cd llvm-project-18.1.8.src/
          cmake -S llvm -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build build
