name: LLVM build

on:
  workflow_dispatch:

env:
  CC: clang
  CXX: clang++
  MAKE: make

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: building
        run: |
          sudo apt install build-essential ninja-build -y
          chmod +x compile.sh
          ./compile.sh
